-- ============================================================
--  Automobile Production Data Security & Workflow Optimization
--  DATABASE SETUP SCRIPT  v2.0  (UPGRADED)
--  Run this ONCE before starting the application.
--  CHANGE: passwords are now stored as salted SHA-256 hashes.
-- ============================================================

CREATE DATABASE IF NOT EXISTS automobile_db;
USE automobile_db;

-- ── TABLE 1: users ──────────────────────────────────────────
-- password column widened to 300 chars to hold salt:hash string
-- is_active: 0 = deactivated by admin, 1 = active (default)
CREATE TABLE IF NOT EXISTS users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(300) NOT NULL,          -- stores "salt:hash" (not plain text)
    role        ENUM('admin','design','analytics','qc','testing') NOT NULL,
    full_name   VARCHAR(100),
    is_active   TINYINT(1) DEFAULT 1,           -- NEW: admin can deactivate users
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── TABLE 2: vehicle ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vehicle (
    id                      INT AUTO_INCREMENT PRIMARY KEY,
    model_name              VARCHAR(100) NOT NULL,
    seating_capacity        INT          NOT NULL,
    fuel_battery_capacity   DOUBLE       NOT NULL,
    fuel_type               ENUM('Petrol','Diesel','Electric','Hybrid') NOT NULL,
    added_by                VARCHAR(50),
    status                  ENUM('pending','approved','rejected') DEFAULT 'pending',
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ── TABLE 3: approvals ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS approvals (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    vehicle_id  INT  NOT NULL,
    action      ENUM('approved','rejected') NOT NULL,
    remarks     TEXT,
    qc_user     VARCHAR(50),
    action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE CASCADE
);

-- ── TABLE 4: testing_status ─────────────────────────────────
CREATE TABLE IF NOT EXISTS testing_status (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    vehicle_id   INT NOT NULL,
    test_type    VARCHAR(100),
    status       ENUM('pending','pass','fail') DEFAULT 'pending',
    test_remarks TEXT,
    tested_by    VARCHAR(50),
    test_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE CASCADE
);

-- ============================================================
--  SAMPLE DATA
--  IMPORTANT: Passwords below are HASHED.
--  Plain-text passwords and their hashes:
--    admin123     → (hash generated by PasswordUtil.hashPassword("admin123"))
--    design123    → (hash generated by PasswordUtil.hashPassword("design123"))
--    ...
--
--  HOW TO GENERATE HASHES:
--  Run the seed utility class SeedPasswords.java once (provided in util package),
--  or use the admin panel after first login.
--
--  For initial testing only — run SeedPasswords.java to insert hashed users.
--  OR use the plain-text SQL below (run PasswordHashSeeder.java to upgrade):
-- ============================================================

-- Temporary seeding using plaintext passwords (ONLY for local dev setup).
-- IMMEDIATELY run SeedPasswords.java after first Tomcat startup to hash them.
INSERT INTO users (username, password, role, full_name, is_active) VALUES
('admin',     'HASH_ME_admin123',     'admin',     'System Administrator', 1),
('designer1', 'HASH_ME_design123',    'design',    'Raj Kumar',            1),
('analyst1',  'HASH_ME_analytics123', 'analytics', 'Priya Sharma',         1),
('qc1',       'HASH_ME_qc123',        'qc',        'Arjun Singh',          1),
('tester1',   'HASH_ME_test123',      'testing',   'Sneha Patel',          1);

-- NOTE: The LoginServlet calls PasswordUtil.verifyPassword(input, storedHash).
-- For the above placeholder values to work, replace them with actual hashes
-- produced by PasswordUtil.hashPassword("admin123") etc.
-- See SeedPasswords.java in the util package for a one-click seeder.

-- 3 Sample Vehicles
INSERT INTO vehicle (model_name, seating_capacity, fuel_battery_capacity, fuel_type, added_by, status) VALUES
('AutoX 3000',   5, 60.0, 'Petrol',   'designer1', 'approved'),
('ElectraV Pro', 7, 80.5, 'Electric', 'designer1', 'pending'),
('HybridMax Z',  4, 45.0, 'Hybrid',   'designer1', 'rejected');

INSERT INTO approvals (vehicle_id, action, remarks, qc_user) VALUES
(1, 'approved', 'All parameters meet production standards.', 'qc1'),
(3, 'rejected', 'Battery capacity below hybrid minimum.',    'qc1');

INSERT INTO testing_status (vehicle_id, test_type, status, test_remarks, tested_by) VALUES
(1, 'Road Performance Test', 'pass', 'Passed all road performance tests.', 'tester1'),
(1, 'Safety & Emission Test','pass', 'Emission levels within limits.',      'tester1');
